// Product -> Fragrantica id, for every active product in the catalog.
//
// Where the ids come from, in precedence order:
//   1. corrected — verified ids read off `lib/catalog/wrong-product-images.ts`, which
//      checked each photograph by eye against the house's own Fragrantica page.
//      Authoritative; nothing here overrides it.
//   2. spree — a unique name match against the legacy Spree manifest
//      (`apps/backend/db/data/product_image_manifest.json`). Not independently
//      re-verified except for a random 30-row sample (2026-09-29): 28 were right; two
//      were wrong and are recorded below with basis 'search' and a note giving the old
//      id. Two more turned up outside the sample: both Baccarat Rouge 540 rows carried
//      the Extrait's id. The other 255 spree rows are unchanged and could hide more of
//      the same kind of error — see the review doc.
//   3. search — resolved by hand (2026-09-29): brand, name, concentration, year and
//      gender searched on the web, and the id accepted only when the brand and the exact
//      perfume matched (flanker words agree; a name with no flanker word points at the
//      base perfume, never a guessed flanker). Also used for the four corrected spree ids
//      and for one unresolved row whose catalog sibling already carried a spree id.
//   4. house — brand 'labor', the shop's own products (cassettes, car perfumes, lotions,
//      diffusers, shower gels, soaps). Most have no specific named original and no
//      Fragrantica page; `fragranticaId` is null.
//   5. inspired — a house product whose own name names a specific existing perfume
//      (e.g. "Avto Parfum Thomas Kosmala №4" is a car freshener scented like Thomas
//      Kosmala's No.4 Après l'Amour). `fragranticaId` is the ORIGINAL's id, found the
//      same way as 'search', with the same base-over-flanker rule. A house product with
//      only a material name (e.g. "Body Lotion Vanilla Milk"), an invented name, or a
//      name that only might name a real perfume stays 'house' with `fragranticaId` null —
//      see the review doc's "possible inspiration" list for the latter.
//   6. unresolved — searched and not found, or found but ambiguous (candidates listed in
//      the review doc). Never guessed: a wrong id is worse than none.
//
// Several ids are shared by more than one slug on purpose — the same perfume sold as
// more than one listing (`aventus` / `aventus-man`), or a labor house line selling the
// same scent as a spray, a home fragrance and a shower gel. The review doc lists the
// shared ids among real listings (basis corrected/spree/search) as likely duplicate
// catalog entries worth a look; sharing between house/inspired rows is expected and not
// listed there.
//
// Built 2026-09-29 from `scripts/out/fragrantica-sources.prefill.json` (485 active
// products). See `scripts/out/fragrantica-sources-review.md` for the unresolved list,
// the shared ids, the possible-inspiration list and the spot-check result.

export interface FragranticaSource {
  readonly slug: string;
  readonly fragranticaId: number | null;
  readonly basis: 'corrected' | 'spree' | 'search' | 'house' | 'inspired' | 'unresolved';
  readonly note?: string;
}

export const FRAGRANTICA_SOURCES: readonly FragranticaSource[] = [
  { slug: 'lovers-cassette', fragranticaId: null, basis: 'house' },
  { slug: 'london-eye-cassette', fragranticaId: null, basis: 'house' },
  { slug: 'santrope-cassette', fragranticaId: null, basis: 'house' },
  { slug: 'ain-dubai-cassette', fragranticaId: null, basis: 'house' },
  { slug: 'car-parfum-orange', fragranticaId: null, basis: 'house' },
  {
    slug: 'wood-sage-sea-salt',
    fragranticaId: 25529,
    basis: 'inspired',
    note: 'inspired by Jo Malone London Wood Sage & Sea Salt',
  },
  {
    slug: 'mr-flakon-20-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'okiii is a wholesale plastic perfume-bottle supplier (Instagram @okiii_flakon), not a fragrance house',
  },
  { slug: 'body-lotion-osmanthus-jasmine', fragranticaId: null, basis: 'house' },
  { slug: 'body-lotion-violet-peach', fragranticaId: null, basis: 'house' },
  { slug: 'body-lotion-vanilla-milk', fragranticaId: null, basis: 'house' },
  { slug: 'acqua-di-gio-profumo', fragranticaId: 29727, basis: 'spree' },
  { slug: 'blue-seduction', fragranticaId: 1088, basis: 'spree' },
  { slug: 'bottled-unlimited', fragranticaId: 22528, basis: 'spree' },
  { slug: 'funny', fragranticaId: 1215, basis: 'spree' },
  { slug: 'uomo-born-in-roma-intense', fragranticaId: 78740, basis: 'spree' },
  { slug: 'donna-born-in-roma-intense', fragranticaId: 78739, basis: 'spree' },
  { slug: 'pour-homme-dylan-blue', fragranticaId: 40031, basis: 'spree' },
  { slug: 'painter', fragranticaId: 54911, basis: 'spree' },
  { slug: 'bal-d-afrique-absolu', fragranticaId: 108421, basis: 'spree' },
  { slug: 'dopamine', fragranticaId: 63835, basis: 'spree' },
  { slug: 'herod', fragranticaId: 16939, basis: 'spree' },
  { slug: 'blanche-bete-les', fragranticaId: 70189, basis: 'spree' },
  { slug: 'torino24', fragranticaId: 99380, basis: 'spree' },
  { slug: 'noir', fragranticaId: 15727, basis: 'corrected' },
  { slug: 'aoud-roja-dove', fragranticaId: 17930, basis: 'corrected' },
  { slug: 'lost-in-paris-roja-dove', fragranticaId: 97481, basis: 'spree' },
  { slug: 'cuir-infrarouge-maison-crivelli', fragranticaId: 96781, basis: 'corrected' },
  { slug: 'le-beau-paradise-garden', fragranticaId: 88836, basis: 'spree' },
  { slug: 'blonde-amber', fragranticaId: 73595, basis: 'spree' },
  {
    slug: 'town-country',
    fragranticaId: 83240,
    basis: 'search',
    note: 'Clive Christian Town & Country — https://www.fragrantica.com/perfume/Clive-Christian/Town-Country-83240.html',
  },
  { slug: 'fugazzi-by', fragranticaId: 99255, basis: 'spree' },
  { slug: 'guidance-46', fragranticaId: 94033, basis: 'spree' },
  { slug: 'colonia-il-profumo', fragranticaId: 100793, basis: 'spree' },
  { slug: 'tygar-x-refik-anadol', fragranticaId: 108062, basis: 'spree' },
  {
    slug: 'avto-parfum-thomas-kosmala-4',
    fragranticaId: 53742,
    basis: 'inspired',
    note: "inspired by Thomas Kosmala No.4 Après l'Amour",
  },
  { slug: 'avto-parfum-bukhoor', fragranticaId: null, basis: 'house' },
  {
    slug: 'avto-parfum-imagination',
    fragranticaId: null,
    basis: 'unresolved',
    note: "car-freshener scented like LV Imagination, not the LV bottle itself; real Imagination is already mapped (slug 'imagination', id 67370)",
  },
  { slug: 'oud-cadenza', fragranticaId: 95195, basis: 'spree' },
  { slug: 'angels-share-paradis-by', fragranticaId: 101629, basis: 'spree' },
  { slug: 'ebene-fume', fragranticaId: 69008, basis: 'spree' },
  { slug: 'telea', fragranticaId: 61876, basis: 'spree' },
  { slug: 'palatine', fragranticaId: 96023, basis: 'spree' },
  { slug: 'castley', fragranticaId: 104991, basis: 'spree' },
  { slug: 'risvelium', fragranticaId: 104365, basis: 'spree' },
  { slug: 'hundred-silent-ways-x', fragranticaId: 80463, basis: 'spree' },
  { slug: 'montabaco-rio-2025', fragranticaId: 101568, basis: 'spree' },
  { slug: 'ani-x', fragranticaId: 80464, basis: 'spree' },
  { slug: 'eau-de-memo', fragranticaId: 44229, basis: 'spree' },
  { slug: 'le-beau-parfum-2025', fragranticaId: 106859, basis: 'spree' },
  { slug: 'santal-volcanique', fragranticaId: 53871, basis: 'spree' },
  { slug: 'safran-secret', fragranticaId: 104728, basis: 'spree' },
  { slug: 'fleur-du-desert', fragranticaId: 73006, basis: 'spree' },
  { slug: 'sun-song-2025', fragranticaId: 107116, basis: 'spree' },
  { slug: 'good-girl-gone-bad-extreme-by', fragranticaId: 43810, basis: 'spree' },
  { slug: 'molecule-05', fragranticaId: 58969, basis: 'spree' },
  { slug: 'royal-mayfair', fragranticaId: 99603, basis: 'spree' },
  { slug: 'oud-zarian', fragranticaId: 111224, basis: 'spree' },
  { slug: 'red-tea-vetiver', fragranticaId: 101977, basis: 'spree' },
  { slug: 'opal', fragranticaId: 102378, basis: 'spree' },
  { slug: 'drunk-lovers', fragranticaId: 81882, basis: 'spree' },
  { slug: 'diffuzor-joly', fragranticaId: null, basis: 'house' },
  { slug: 'diffuzor-black-vanilla', fragranticaId: null, basis: 'house' },
  {
    slug: 'magnit-flakon-10-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'okiii bottle supplier, not a fragrance',
  },
  { slug: 'luna-rossa-carbon', fragranticaId: 43402, basis: 'spree' },
  { slug: 'boss-bottled-elixir', fragranticaId: 84074, basis: 'spree' },
  { slug: 'boss-bottled-sport', fragranticaId: 14597, basis: 'spree' },
  { slug: 'aqva-pour-homme-marine', fragranticaId: 1742, basis: 'spree' },
  { slug: 'very-sexy-night', fragranticaId: 114424, basis: 'spree' },
  { slug: 'allure-homme-sport', fragranticaId: 607, basis: 'corrected' },
  { slug: 'j-adore', fragranticaId: 51818, basis: 'spree' },
  { slug: 'english-pear', fragranticaId: 10314, basis: 'spree' },
  { slug: 'nice-bergamote', fragranticaId: 50789, basis: 'spree' },
  { slug: 'halley', fragranticaId: 55007, basis: 'spree' },
  { slug: 'patchouli-magnetik', fragranticaId: 71759, basis: 'spree' },
  { slug: 'purpose-50', fragranticaId: 100897, basis: 'spree' },
  { slug: 'red-tobacco', fragranticaId: 46663, basis: 'spree' },
  { slug: 'pink-pepper-elemi-cinnamon-leather', fragranticaId: 108569, basis: 'spree' },
  { slug: 'althair', fragranticaId: 84109, basis: 'spree' },
  { slug: 'florentine-iris', fragranticaId: 70636, basis: 'spree' },
  { slug: 'fierce', fragranticaId: 3508, basis: 'spree' },
  { slug: 'aqua-celestia', fragranticaId: 42268, basis: 'spree' },
  { slug: 'oud-for-greatness-neo-initio-parfums-prives', fragranticaId: 93090, basis: 'spree' },
  { slug: 'hanuman', fragranticaId: 35525, basis: 'spree' },
  { slug: 'blue-heart', fragranticaId: 75055, basis: 'spree' },
  {
    slug: 'ganymede-extrait',
    fragranticaId: 79632,
    basis: 'search',
    note: 'Marc-Antoine Barrois Ganymede Extrait — https://www.fragrantica.com/perfume/Marc-Antoine-Barrois/Ganymede-Extrait-79632.html',
  },
  { slug: 'jazz-club-maison-martin-margiela', fragranticaId: 119443, basis: 'spree' },
  { slug: 'oud-wood', fragranticaId: 1826, basis: 'corrected' },
  { slug: 'meteore', fragranticaId: 62251, basis: 'spree' },
  { slug: 'not-a-perfume', fragranticaId: 10296, basis: 'spree' },
  { slug: 'jump-up-and-kiss-me-hedonistic-2021', fragranticaId: 70767, basis: 'spree' },
  { slug: 'escentric-02', fragranticaId: 112764, basis: 'spree' },
  { slug: 'torino22', fragranticaId: 77059, basis: 'spree' },
  {
    slug: 'savon-krem-milo-relax-500-gr',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'savon-krem-milo-thermal-spa-500-gr',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'savon-krem-milo-natural-500-gr',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'savon-krem-milo-romance-500-gr',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-blue-400-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-melon-400-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-crystal-400-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-citiboy-400-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-blue-100-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-melon-100-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-fleur-100-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-crystal-100-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-citiboy-100-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  {
    slug: 'antiseptik-sofderm-extra-50-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Sofderm is an Uzbek antiseptic/soap brand; no Fragrantica listing',
  },
  { slug: 'love-don-t-be-shy-by', fragranticaId: 4322, basis: 'corrected' },
  {
    slug: 'mefisto-gentiluomo-xerjoff',
    fragranticaId: null,
    basis: 'unresolved',
    note: "Casa Tito is a reseller label, not on Fragrantica; name echoes Xerjoff/Casamorati but isn't sold under that brand",
  },
  { slug: 'bergamask', fragranticaId: 24191, basis: 'spree' },
  { slug: 'the-muse', fragranticaId: 60665, basis: 'spree' },
  { slug: 'paragon-initio-parfums-prives', fragranticaId: 76580, basis: 'spree' },
  { slug: 'lamar', fragranticaId: 62571, basis: 'spree' },
  { slug: 'eladaria', fragranticaId: 103066, basis: 'spree' },
  { slug: 'narcotic-delight-initio-parfums-prives', fragranticaId: 89368, basis: 'spree' },
  { slug: 'kurky', fragranticaId: 103517, basis: 'spree' },
  { slug: 'valaya', fragranticaId: 78574, basis: 'spree' },
  { slug: 'terre-d-herm-s-intense', fragranticaId: 50679, basis: 'spree' },
  { slug: 'fragaria', fragranticaId: 100641, basis: 'spree' },
  { slug: 'miss-dior-blooming-bouquet', fragranticaId: 78945, basis: 'corrected' },
  { slug: 'marijuana', fragranticaId: 50002, basis: 'corrected' },
  {
    slug: 'kalso-10',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'okiii bottle supplier, not a fragrance',
  },
  {
    slug: 'kalso-20',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'okiii bottle supplier, not a fragrance',
  },
  { slug: 'aldebaran', fragranticaId: 105331, basis: 'spree' },
  { slug: 'elves', fragranticaId: 122132, basis: 'spree' },
  { slug: 'chance-eau-splendide', fragranticaId: 104610, basis: 'spree' },
  {
    slug: 'lunario',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Casa Tito is a reseller label; no Fragrantica listing',
  },
  {
    slug: 'vanoria',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Casa Tito is a reseller label; no Fragrantica listing',
  },
  {
    slug: 'muscavilla',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Casa Tito is a reseller label; no Fragrantica listing',
  },
  { slug: 'symphony-300', fragranticaId: null, basis: 'house' },
  {
    slug: 'good-girl-gone-bad-300',
    fragranticaId: 15924,
    basis: 'inspired',
    note: 'inspired by By Kilian Good Girl Gone Bad',
  },
  {
    slug: 'molecula-020-300',
    fragranticaId: 3606,
    basis: 'inspired',
    note: 'inspired by Escentric Molecules Molecule 02',
  },
  { slug: 'flora-300', fragranticaId: null, basis: 'house' },
  {
    slug: 'my-way-300-gr',
    fragranticaId: 62036,
    basis: 'inspired',
    note: 'inspired by Giorgio Armani My Way',
  },
  {
    slug: 'ecstasy-collection',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Casa Tito is a reseller label; no Fragrantica listing',
  },
  {
    slug: 'euphoria-collection',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Casa Tito is a reseller label; no Fragrantica listing',
  },
  {
    slug: 'megamare-50-ml',
    fragranticaId: 53471,
    basis: 'inspired',
    note: 'inspired by Orto Parisi Megamare',
  },
  { slug: 'symphony-50-ml', fragranticaId: null, basis: 'house' },
  {
    slug: 'molecule-02-50-ml',
    fragranticaId: 3606,
    basis: 'inspired',
    note: 'inspired by Escentric Molecules Molecule 02',
  },
  {
    slug: 'ombre-leather-50-ml',
    fragranticaId: 50239,
    basis: 'inspired',
    note: 'inspired by Tom Ford Ombré Leather',
  },
  {
    slug: 'ganymed-50-ml',
    fragranticaId: 54720,
    basis: 'inspired',
    note: 'inspired by Marc-Antoine Barrois Ganymede',
  },
  {
    slug: 'my-way-50-ml',
    fragranticaId: 62036,
    basis: 'inspired',
    note: 'inspired by Giorgio Armani My Way',
  },
  {
    slug: 'black-code-50-ml',
    fragranticaId: 412,
    basis: 'inspired',
    note: 'inspired by Giorgio Armani Black Code (Armani Code)',
  },
  {
    slug: 'black-afgano-50-ml',
    fragranticaId: 6472,
    basis: 'inspired',
    note: 'inspired by Nasomatto Black Afgano',
  },
  {
    slug: 'tygar-50-ml',
    fragranticaId: 41222,
    basis: 'inspired',
    note: 'inspired by Bvlgari Tygar',
  },
  {
    slug: 'kissing-burns-6-4-calories',
    fragranticaId: 50496,
    basis: 'search',
    note: 'By Kilian Kissing Burns 6.4 Calories A Minute. Wanna Workout? — https://www.fragrantica.com/perfume/By-Kilian/Kissing-Burns-6-4-Calories-A-Minute-Wanna-Workout-50496.html',
  },
  {
    slug: 'diffuzor-rosso-nobili',
    fragranticaId: 80244,
    basis: 'inspired',
    note: 'inspired by Dr. Vranjes Firenze Rosso Nobile',
  },
  {
    slug: 'tygar-220-ml',
    fragranticaId: 41222,
    basis: 'inspired',
    note: 'inspired by Bvlgari Tygar',
  },
  { slug: '20-c', fragranticaId: null, basis: 'house' },
  { slug: 'indian-venus-haute-fragrance-company', fragranticaId: 52793, basis: 'spree' },
  { slug: 'angels-share-by', fragranticaId: 62615, basis: 'corrected' },
  { slug: 'more-than-words', fragranticaId: 15552, basis: 'spree' },
  { slug: 'delina-exclusif', fragranticaId: 50370, basis: 'spree' },
  {
    slug: 'montabaco-50-ml',
    fragranticaId: 16896,
    basis: 'inspired',
    note: 'inspired by Ormonde Jayne Montabaco',
  },
  {
    slug: 'good-girl-gone-bad-50-ml',
    fragranticaId: 15924,
    basis: 'inspired',
    note: 'inspired by By Kilian Good Girl Gone Bad',
  },
  {
    slug: 'limmensite-50-ml',
    fragranticaId: 49751,
    basis: 'inspired',
    note: "inspired by Louis Vuitton L'Immensité",
  },
  {
    slug: 'aventus-50-ml',
    fragranticaId: 9828,
    basis: 'inspired',
    note: 'inspired by Creed Aventus',
  },
  {
    slug: 'sauvage-50-ml',
    fragranticaId: 31861,
    basis: 'inspired',
    note: 'inspired by Dior Sauvage',
  },
  {
    slug: 'tobacco-vanille-50-ml',
    fragranticaId: 1825,
    basis: 'inspired',
    note: 'inspired by Tom Ford Tobacco Vanille',
  },
  { slug: 'flora-50-ml', fragranticaId: null, basis: 'house' },
  { slug: 'elysium-50-ml', fragranticaId: null, basis: 'house' },
  {
    slug: 'eyphoria',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Casa Tito is a reseller label, a perfumed cream; no Fragrantica listing',
  },
  {
    slug: 'ecstasy',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Casa Tito is a reseller label, a body cream; no Fragrantica listing',
  },
  { slug: 'flakon-koja-louivitton', fragranticaId: null, basis: 'house' },
  { slug: 'flakon-koja-kvadrat', fragranticaId: null, basis: 'house' },
  { slug: 'flakon-koja-zeleniy', fragranticaId: null, basis: 'house' },
  { slug: 'flakon-koja-roziviy', fragranticaId: null, basis: 'house' },
  { slug: 'flakon-koja-orang', fragranticaId: null, basis: 'house' },
  { slug: 'mango-skin', fragranticaId: 49305, basis: 'spree' },
  { slug: 'cedre-atlas', fragranticaId: 30045, basis: 'spree' },
  { slug: 'gran-ballo-casa-moratti', fragranticaId: 26708, basis: 'corrected' },
  {
    slug: 'replica-lazy-sunday-morning-maison-martin-margiela',
    fragranticaId: 20542,
    basis: 'spree',
  },
  { slug: 'dear-polly', fragranticaId: 30928, basis: 'corrected' },
  {
    slug: 'black-eyes',
    fragranticaId: null,
    basis: 'unresolved',
    note: "no 'Never Lies' house on Fragrantica; a same-named Black Eyes exists under Ladanika, a different brand",
  },
  { slug: 'cedrat-boise', fragranticaId: 15211, basis: 'spree' },
  {
    slug: 'liebe',
    fragranticaId: 22910,
    basis: 'search',
    note: 'Khaltat Liebe — https://www.fragrantica.com/perfume/Khaltat/Liebe-22910.html',
  },
  { slug: 'gris-charnel', fragranticaId: 57038, basis: 'spree' },
  {
    slug: 'n5-floral-amber-sensual',
    fragranticaId: 46115,
    basis: 'search',
    note: 'Rosendo Mateu Olfactive Expressions Nº5 Floral, Amber, Sensual Musk — https://www.fragrantica.com/perfume/Rosendo-Mateu-Olfactive-Expressions/Rosendo-Mateu-No-5-Floral-Amber-Sensual-Musk-46115.html',
  },
  { slug: 'kinski', fragranticaId: 14192, basis: 'spree' },
  { slug: 'n4-apr-s-l-amour', fragranticaId: 53742, basis: 'spree' },
  { slug: 'id-le-lanc-me', fragranticaId: 120731, basis: 'spree' },
  { slug: 'tuxedo', fragranticaId: 32269, basis: 'spree' },
  { slug: 'fahrenheit-32', fragranticaId: 987, basis: 'corrected' },
  { slug: 'fucking-fabulous', fragranticaId: 46513, basis: 'spree' },
  { slug: 'tuscan-leather', fragranticaId: 1849, basis: 'spree' },
  { slug: 'cherry-smoke', fragranticaId: 78578, basis: 'corrected' },
  { slug: 'electric-cherry', fragranticaId: 78583, basis: 'corrected' },
  { slug: 'silver-mountain-water', fragranticaId: 472, basis: 'corrected' },
  { slug: 'jardin-d-amalfi', fragranticaId: 13389, basis: 'spree' },
  { slug: 'i-don-t-need-a-prince-rose-de-mai-by', fragranticaId: 57939, basis: 'spree' },
  { slug: 'accento', fragranticaId: 55156, basis: 'spree' },
  { slug: 'alexandria-ii', fragranticaId: 19655, basis: 'spree' },
  { slug: 'aqua-media-cologne-forte-maison', fragranticaId: 82030, basis: 'spree' },
  { slug: '724-maison', fragranticaId: 75754, basis: 'spree' },
  { slug: 'baccarat-extrait-maison', fragranticaId: 46066, basis: 'spree' },
  { slug: 'amyris-femme-maison', fragranticaId: 15565, basis: 'spree' },
  { slug: 'x-for-women', fragranticaId: 4652, basis: 'spree' },
  { slug: '1872-for-men', fragranticaId: 4646, basis: 'spree' },
  { slug: 'aventus-for-her', fragranticaId: 38498, basis: 'spree' },
  { slug: 'egoiste', fragranticaId: 17293, basis: 'spree' },
  { slug: 'coco-mademoiselle-parfum', fragranticaId: 6928, basis: 'spree' },
  {
    slug: 'good-girl',
    fragranticaId: 39681,
    basis: 'search',
    note: 'Carolina Herrera Good Girl — https://www.fragrantica.com/perfume/Carolina-Herrera/Good-Girl-39681.html',
  },
  { slug: 'si', fragranticaId: 18453, basis: 'corrected' },
  { slug: 'my-way', fragranticaId: 62036, basis: 'spree' },
  { slug: 'au-hasard', fragranticaId: 49756, basis: 'spree' },
  { slug: 'myriad', fragranticaId: 85363, basis: 'spree' },
  {
    slug: 'on-the-beach',
    fragranticaId: 66060,
    basis: 'search',
    note: 'Louis Vuitton On The Beach — https://www.fragrantica.com/perfume/Louis-Vuitton/On-The-Beach-66060.html',
  },
  { slug: 'stellar-times', fragranticaId: 68356, basis: 'spree' },
  { slug: 'city-of-stars', fragranticaId: 73344, basis: 'spree' },
  { slug: 'the-hedonist', fragranticaId: 96233, basis: 'spree' },
  { slug: 'blue-talisman', fragranticaId: 84224, basis: 'corrected' },
  { slug: 'fleur-narcotique-extrait-de-parfum', fragranticaId: 75061, basis: 'spree' },
  { slug: 'apex-roja-dove', fragranticaId: 103275, basis: 'spree' },
  { slug: 'manhattan-roja-dove', fragranticaId: 77295, basis: 'spree' },
  { slug: 'blackberry-bay', fragranticaId: 15134, basis: 'spree' },
  { slug: 'irish-leather', fragranticaId: 18393, basis: 'spree' },
  { slug: 'oud-for-greatness-initio-parfums-prives', fragranticaId: 53641, basis: 'corrected' },
  { slug: 'hayati', fragranticaId: 50344, basis: 'corrected' },
  { slug: 'cl-mentine-california', fragranticaId: 42249, basis: 'spree' },
  { slug: 'molecule-01', fragranticaId: 845, basis: 'corrected' },
  { slug: 'molecule-01-iris', fragranticaId: 66048, basis: 'spree' },
  { slug: 'la-tosca-casa-morati', fragranticaId: 32191, basis: 'corrected' },
  { slug: 'halfeti-leather', fragranticaId: 61523, basis: 'spree' },
  { slug: 'constantinople', fragranticaId: 68998, basis: 'spree' },
  { slug: 'blue-sapphire', fragranticaId: 18518, basis: 'spree' },
  { slug: 'intense-cafe', fragranticaId: 18021, basis: 'corrected' },
  { slug: 'megamare', fragranticaId: 53471, basis: 'corrected' },
  { slug: 'gumin', fragranticaId: 40440, basis: 'corrected' },
  { slug: 'andromeda', fragranticaId: 30623, basis: 'spree' },
  {
    slug: 'divine-blossom-haute-fragrance-company',
    fragranticaId: 70785,
    basis: 'search',
    note: 'Haute Fragrance Company HFC Divine Blossom — https://www.fragrantica.com/perfume/Haute-Fragrance-Company-HFC/Divine-Blossom-70785.html',
  },
  { slug: 'tygar-300', fragranticaId: 41222, basis: 'inspired', note: 'inspired by Bvlgari Tygar' },
  {
    slug: 'lelabo-santal-33-220-ml',
    fragranticaId: 12201,
    basis: 'inspired',
    note: 'inspired by Le Labo Santal 33',
  },
  {
    slug: 'limmensite-220-ml',
    fragranticaId: 49751,
    basis: 'inspired',
    note: "inspired by Louis Vuitton L'Immensité",
  },
  {
    slug: 'chanel-chance-220-ml',
    fragranticaId: 610,
    basis: 'inspired',
    note: 'inspired by Chanel Chance',
  },
  {
    slug: 'tomford-lostcherry-220-ml',
    fragranticaId: 51411,
    basis: 'inspired',
    note: 'inspired by Tom Ford Lost Cherry',
  },
  {
    slug: 'creed-aventus-220-ml',
    fragranticaId: 9828,
    basis: 'inspired',
    note: 'inspired by Creed Aventus',
  },
  {
    slug: 'kirke-220-ml',
    fragranticaId: 32172,
    basis: 'inspired',
    note: 'inspired by Tiziana Terenzi Kirkè',
  },
  {
    slug: 'black-afgano-220-ml',
    fragranticaId: 6472,
    basis: 'inspired',
    note: 'inspired by Nasomatto Black Afgano',
  },
  {
    slug: 'maison-baccarat-220-ml',
    fragranticaId: 33519,
    basis: 'inspired',
    note: 'inspired by Maison Francis Kurkdjian Baccarat Rouge 540',
  },
  {
    slug: 'bright-crystal-220-ml',
    fragranticaId: 632,
    basis: 'inspired',
    note: 'inspired by Versace Bright Crystal',
  },
  {
    slug: 'chanel-sport-220-ml',
    fragranticaId: 607,
    basis: 'inspired',
    note: 'inspired by Chanel Allure Homme Sport',
  },
  {
    slug: 'chanel-bleu-220-ml',
    fragranticaId: null,
    basis: 'unresolved',
    note: "labor's own 220 ml home spray, not the Chanel bottle",
  },
  {
    slug: 'bulgari-aqua-220-ml',
    fragranticaId: 153,
    basis: 'inspired',
    note: 'inspired by Bvlgari Aqua pour Homme',
  },
  { slug: 'california-dream', fragranticaId: 60388, basis: 'spree' },
  { slug: 'l-immensit', fragranticaId: 49751, basis: 'spree' },
  { slug: '20-iconic-masculin', fragranticaId: 57887, basis: 'spree' },
  { slug: 'french-lover', fragranticaId: 1022, basis: 'spree' },
  { slug: 'vanilla-blend', fragranticaId: 65069, basis: 'spree' },
  { slug: 'torino21', fragranticaId: 70424, basis: 'spree' },
  { slug: 'soleil-blanc', fragranticaId: 34893, basis: 'spree' },
  { slug: 'the-omniscient-mr-thompson', fragranticaId: 84254, basis: 'spree' },
  { slug: 'boccanera', fragranticaId: 24195, basis: 'spree' },
  { slug: 'lv-lovers', fragranticaId: 93785, basis: 'spree' },
  { slug: 'le-male-lover', fragranticaId: 89720, basis: 'spree' },
  {
    slug: 'fleur-narcotique',
    fragranticaId: 27571,
    basis: 'search',
    note: 'Ex Nihilo Fleur Narcotique (base EDP) — https://www.fragrantica.com/perfume/Ex-Nihilo/Fleur-Narcotique-27571.html',
  },
  { slug: 'vanilla-diorama', fragranticaId: 68198, basis: 'spree' },
  { slug: 'matsukita', fragranticaId: 65983, basis: 'spree' },
  { slug: 'bal-d-afrique', fragranticaId: 6458, basis: 'corrected' },
  { slug: 'emporio-armani-stronger-with-you', fragranticaId: 45258, basis: 'corrected' },
  { slug: 'english-pear-freesia', fragranticaId: 10314, basis: 'spree' },
  { slug: 'symphony', fragranticaId: 68357, basis: 'spree' },
  { slug: 'fan-your-flames', fragranticaId: 37603, basis: 'spree' },
  { slug: 'eau-so-sexy', fragranticaId: 26453, basis: 'spree' },
  { slug: 'molecule-01-mandarin', fragranticaId: 66047, basis: 'spree' },
  { slug: 'accento-sospiro-perfumes', fragranticaId: 13816, basis: 'spree' },
  {
    slug: 'baccarat-rouge-540-maison',
    fragranticaId: 33519,
    basis: 'search',
    note: "Maison Francis Kurkdjian Baccarat Rouge 540 (base eau de parfum, 2015) — https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html; spree gave 46066, the Extrait de Parfum, but the name has no 'Extrait'",
  },
  { slug: 'herbes-troublantes', fragranticaId: 69275, basis: 'corrected' },
  { slug: 'ma-vie-l-eau', fragranticaId: 48092, basis: 'spree' },
  { slug: 'resala', fragranticaId: 53104, basis: 'spree' },
  { slug: 'london', fragranticaId: 47781, basis: 'spree' },
  { slug: 'white-lacoste-fragrances', fragranticaId: 11043, basis: 'spree' },
  { slug: 'summer-hammer', fragranticaId: 81476, basis: 'spree' },
  { slug: 'rose-blush-cologne-2024', fragranticaId: 89143, basis: 'spree' },
  { slug: 'light-blue', fragranticaId: 485, basis: 'spree' },
  { slug: 'hajar-aswad', fragranticaId: 50856, basis: 'spree' },
  { slug: 'one-umbrella-for-two', fragranticaId: 46165, basis: 'spree' },
  { slug: 'the-blazing-mr-sam', fragranticaId: 50255, basis: 'spree' },
  { slug: 'h01', fragranticaId: 83318, basis: 'spree' },
  { slug: 'escentric-01', fragranticaId: 846, basis: 'corrected' },
  { slug: 'delicate-rose', fragranticaId: 16241, basis: 'spree' },
  { slug: 'orange-jasmine-vanilla', fragranticaId: 65053, basis: 'spree' },
  { slug: 'fiction', fragranticaId: 65065, basis: 'spree' },
  { slug: 'black-pepper-amber-neroli', fragranticaId: 65074, basis: 'spree' },
  { slug: 'mol-cule-c-19-the-beach', fragranticaId: 91715, basis: 'spree' },
  {
    slug: 'pink-mol-cule-090-09',
    fragranticaId: 25474,
    basis: 'search',
    note: 'ZARKOPERFUME PINK MOLéCULE 090.09 — https://www.fragrantica.com/perfume/ZARKOPERFUME/PINK-MOLeCULE-090-09-25474.html',
  },
  { slug: 'black-opium', fragranticaId: 48042, basis: 'spree' },
  {
    slug: 'libre',
    fragranticaId: 56077,
    basis: 'search',
    note: "was spree id 102207; Yves Saint Laurent Libre (base EDP, 2019) — https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-56077.html; spree id 102207 is 'Libre L'Eau Nue', a 2025 alcohol-free flanker, wrong format for an EDP SKU",
  },
  {
    slug: 'mefisto-casa-moratti',
    fragranticaId: null,
    basis: 'unresolved',
    note: "Casa Tito is a reseller label; name echoes Casamorati but isn't sold under that brand",
  },
  { slug: 'erba-pura', fragranticaId: 55157, basis: 'corrected' },
  { slug: 'xj-1861-naxos', fragranticaId: 30529, basis: 'spree' },
  { slug: 'bombshell', fragranticaId: 10190, basis: 'corrected' },
  { slug: 'narcos-is', fragranticaId: 47923, basis: 'spree' },
  { slug: 'tobacco-oud', fragranticaId: 21402, basis: 'corrected' },
  { slug: 'n-roli-outrenoir', fragranticaId: 40345, basis: 'spree' },
  { slug: 'vanilla-sex', fragranticaId: 88588, basis: 'spree' },
  { slug: 'tobacco-vanille', fragranticaId: 1825, basis: 'corrected' },
  { slug: 'black-orchid', fragranticaId: 1018, basis: 'spree' },
  { slug: 'bitter-peach', fragranticaId: 62707, basis: 'spree' },
  { slug: 'ombr-leather-parfum', fragranticaId: 68716, basis: 'spree' },
  { slug: 'nottebuia', fragranticaId: 88074, basis: 'spree' },
  { slug: 'kirke', fragranticaId: 32172, basis: 'corrected' },
  { slug: 'l-air-du-desert-marocain', fragranticaId: 4573, basis: 'corrected' },
  { slug: 'royal-eagle-sport', fragranticaId: 47524, basis: 'spree' },
  { slug: 'oligarch-roja-dove', fragranticaId: 40687, basis: 'spree' },
  { slug: 'elysium-roja-dove', fragranticaId: 96989, basis: 'spree' },
  { slug: 'isola-blu-roja-dove', fragranticaId: 80177, basis: 'spree' },
  { slug: 'aqua-sapphire', fragranticaId: 69347, basis: 'spree' },
  { slug: 'the-inimitable-william-penhaligon', fragranticaId: 63969, basis: 'spree' },
  { slug: 'the-tragedy-of-lord-george', fragranticaId: 40716, basis: 'spree' },
  { slug: 'layton', fragranticaId: 39314, basis: 'spree' },
  { slug: 'delina', fragranticaId: 43871, basis: 'corrected' },
  { slug: 'sedley', fragranticaId: 56273, basis: 'corrected' },
  { slug: 'greenley', fragranticaId: 62101, basis: 'spree' },
  { slug: 'perseus', fragranticaId: 90199, basis: 'spree' },
  { slug: 'cuoium', fragranticaId: 69923, basis: 'spree' },
  { slug: 'terroni', fragranticaId: 45475, basis: 'spree' },
  { slug: 'montabaco-verano', fragranticaId: 60087, basis: 'spree' },
  { slug: 'osmanthus', fragranticaId: 4923, basis: 'spree' },
  { slug: 'montabaco', fragranticaId: 16896, basis: 'corrected' },
  { slug: 'hacivat', fragranticaId: 44174, basis: 'corrected' },
  { slug: 'karagoz', fragranticaId: 44176, basis: 'spree' },
  { slug: 'wul-ng-ch', fragranticaId: 30567, basis: 'spree' },
  { slug: 'hacivat-x', fragranticaId: 80462, basis: 'spree' },
  { slug: 'black-afgano', fragranticaId: 6472, basis: 'spree' },
  { slug: 'narciso-poudree', fragranticaId: 36679, basis: 'spree' },
  { slug: 'roses-musk', fragranticaId: 1148, basis: 'spree' },
  { slug: 'chocolate-greedy', fragranticaId: 2186, basis: 'spree' },
  { slug: 'molecule-01-black-tea', fragranticaId: 79414, basis: 'spree' },
  { slug: 'molecule-02', fragranticaId: 3606, basis: 'spree' },
  { slug: 'molecule-04', fragranticaId: 44315, basis: 'spree' },
  { slug: 'marfa', fragranticaId: 37185, basis: 'spree' },
  { slug: 'falcon-leather', fragranticaId: 96042, basis: 'spree' },
  { slug: 'parisian-musc', fragranticaId: 59063, basis: 'spree' },
  { slug: 'tub-reuse-astrale', fragranticaId: 90733, basis: 'spree' },
  { slug: 'hibiscus-mahaj-d', fragranticaId: 69069, basis: 'spree' },
  { slug: 'oud-maracuj', fragranticaId: 83842, basis: 'spree' },
  { slug: 'cactus-garden', fragranticaId: 53946, basis: 'corrected' },
  { slug: 'ombre-nomade', fragranticaId: 49755, basis: 'corrected' },
  { slug: 'pur-oud', fragranticaId: 66436, basis: 'spree' },
  { slug: 'pacific-chill', fragranticaId: 81423, basis: 'spree' },
  { slug: 'sur-la-route', fragranticaId: 49754, basis: 'spree' },
  { slug: 'dancing-blossom', fragranticaId: 68358, basis: 'spree' },
  {
    slug: 'afternoon-swim',
    fragranticaId: 53947,
    basis: 'search',
    note: 'Louis Vuitton Afternoon Swim — https://www.fragrantica.com/perfume/Louis-Vuitton/Afternoon-Swim-53947.html',
  },
  { slug: 'bergamote-22', fragranticaId: 6327, basis: 'spree' },
  { slug: 'another-13', fragranticaId: 10131, basis: 'corrected' },
  {
    slug: 'santal-33',
    fragranticaId: 12201,
    basis: 'search',
    note: 'Le Labo Santal 33 — https://www.fragrantica.com/perfume/Le-Labo/Santal-33-12201.html',
  },
  { slug: 'oud-satin-mood-maison', fragranticaId: 30352, basis: 'corrected' },
  { slug: 'gentle-fluidity-gold-maison', fragranticaId: 53401, basis: 'spree' },
  { slug: 'grand-soir-maison', fragranticaId: 40816, basis: 'corrected' },
  { slug: 'straight-to-heaven-by', fragranticaId: 4323, basis: 'spree' },
  { slug: 'princess-by', fragranticaId: 50497, basis: 'spree' },
  {
    slug: 'apple-brandy-by',
    fragranticaId: 22614,
    basis: 'search',
    note: 'By Kilian Apple Brandy (base) — https://www.fragrantica.com/perfume/By-Kilian/Apple-Brandy-22614.html',
  },
  { slug: 'playing-with-the-devil-by', fragranticaId: 18931, basis: 'spree' },
  { slug: 'black-phantom-by', fragranticaId: 43632, basis: 'spree' },
  { slug: 'smoking-hot-by', fragranticaId: 84413, basis: 'spree' },
  {
    slug: 'good-girl-gone-bad-by',
    fragranticaId: 15924,
    basis: 'search',
    note: 'By Kilian Good Girl Gone Bad (base) — https://www.fragrantica.com/perfume/By-Kilian/Good-Girl-Gone-Bad-15924.html',
  },
  { slug: 'moonlight-in-heaven-by', fragranticaId: 35973, basis: 'spree' },
  { slug: 'blue-moon-ginger-dash-by', fragranticaId: 79731, basis: 'spree' },
  { slug: 'oudgasm-vanilla-oud-36', fragranticaId: 85184, basis: 'corrected' },
  { slug: 'le-male-elixir', fragranticaId: 101529, basis: 'spree' },
  { slug: 'le-beau-le-parfum', fragranticaId: 72158, basis: 'spree' },
  {
    slug: 'la-belle',
    fragranticaId: 55786,
    basis: 'search',
    note: "was spree id 122214; Jean Paul Gaultier La Belle (base, 2019) — https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/La-Belle-55786.html; spree id 122214 is 'La Belle Rosea', a 2026 flanker not named on this SKU",
  },
  {
    slug: 'le-beau',
    fragranticaId: 55785,
    basis: 'search',
    note: 'Jean Paul Gaultier Le Beau (base) — https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Beau-55785.html',
  },
  { slug: 'oud-for-happiness', fragranticaId: 69224, basis: 'corrected' },
  {
    slug: 'devil-s-intrigue-haute',
    fragranticaId: 52792,
    basis: 'search',
    note: "Haute Fragrance Company HFC Devil's Intrigue — https://www.fragrantica.com/perfume/Haute-Fragrance-Company-HFC/Devil-s-Intrigue-52792.html",
  },
  { slug: 'terre-d', fragranticaId: 17, basis: 'corrected' },
  { slug: 'rose-centifolia-extrait-1', fragranticaId: 87535, basis: 'spree' },
  { slug: 'the-voice-of-the-snake-parfum', fragranticaId: 53088, basis: 'corrected' },
  { slug: 'flora-by-gucci-eau-fraiche', fragranticaId: 11775, basis: 'spree' },
  { slug: 'tutu', fragranticaId: 54822, basis: 'spree' },
  { slug: 'chandigarh-express', fragranticaId: 89719, basis: 'spree' },
  { slug: 'miss-dior-cherie', fragranticaId: 11399, basis: 'spree' },
  { slug: 'sauvage-elixir', fragranticaId: 68415, basis: 'spree' },
  {
    slug: 'sauvage',
    fragranticaId: 31861,
    basis: 'search',
    note: 'Dior Sauvage (base) — https://www.fragrantica.com/perfume/Dior/Sauvage-31861.html',
  },
  { slug: 'homme-intense', fragranticaId: 13016, basis: 'spree' },
  { slug: 'fahrenheit', fragranticaId: 228, basis: 'corrected' },
  { slug: 'dahab', fragranticaId: 32266, basis: 'spree' },
  { slug: 'delphinus', fragranticaId: 95970, basis: 'spree' },
  { slug: 'centaurus', fragranticaId: 95601, basis: 'spree' },
  { slug: 'original-vetiver', fragranticaId: 99804, basis: 'spree' },
  { slug: 'queen-of-silk', fragranticaId: 89643, basis: 'spree' },
  { slug: 'wind-flowers', fragranticaId: 70182, basis: 'spree' },
  { slug: 'aventus', fragranticaId: 9828, basis: 'corrected' },
  { slug: 'absolu-aventus', fragranticaId: 106624, basis: 'spree' },
  { slug: 'x-for-men', fragranticaId: 4650, basis: 'spree' },
  { slug: 'jump-up-and-kiss-me', fragranticaId: 70767, basis: 'spree' },
  { slug: 'chance-eau-fraiche', fragranticaId: 1483, basis: 'spree' },
  { slug: 'chance-eau-tendre', fragranticaId: 8069, basis: 'spree' },
  { slug: '212-men', fragranticaId: 297, basis: 'corrected' },
  { slug: 'gypsy-water', fragranticaId: 3575, basis: 'corrected' },
  { slug: '1996-inez-vinoodh', fragranticaId: 19247, basis: 'spree' },
  { slug: 'blanche', fragranticaId: 46222, basis: 'spree' },
  { slug: 'tobacco-mandarin', fragranticaId: 63031, basis: 'spree' },
  { slug: 'mojave-ghost', fragranticaId: 27040, basis: 'corrected' },
  {
    slug: 'tygar',
    fragranticaId: 41222,
    basis: 'search',
    note: 'Bvlgari Tygar (base) — https://www.fragrantica.com/perfume/Bvlgari/Tygar-41222.html',
  },
  { slug: 'dragon', fragranticaId: 90202, basis: 'spree' },
  { slug: 'aurica', fragranticaId: 58545, basis: 'spree' },
  { slug: 'ganymede', fragranticaId: 54720, basis: 'corrected' },
  { slug: 'encelade', fragranticaId: 74121, basis: 'spree' },
  { slug: 'tilia', fragranticaId: 91688, basis: 'spree' },
  { slug: 'musk-kashmir', fragranticaId: 102064, basis: 'spree' },
  { slug: 'guidance', fragranticaId: 78656, basis: 'corrected' },
  { slug: 'interlude-man', fragranticaId: 15294, basis: 'corrected' },
  { slug: 'amber-wood', fragranticaId: 26016, basis: 'corrected' },
  { slug: 'boc-27674', fragranticaId: null, basis: 'house' },
  {
    slug: 'imagination-300-gr',
    fragranticaId: 67370,
    basis: 'inspired',
    note: 'inspired by Louis Vuitton Imagination',
  },
  { slug: 'epy-76014', fragranticaId: null, basis: 'house' },
  {
    slug: 'limmensite-300-gr',
    fragranticaId: 49751,
    basis: 'inspired',
    note: "inspired by Louis Vuitton L'Immensité",
  },
  { slug: 'symphony-300-gr', fragranticaId: null, basis: 'house' },
  {
    slug: 'lost-cherry-300-gr',
    fragranticaId: 51411,
    basis: 'inspired',
    note: 'inspired by Tom Ford Lost Cherry',
  },
  {
    slug: 'kirke-300-gr',
    fragranticaId: 32172,
    basis: 'inspired',
    note: 'inspired by Tiziana Terenzi Kirkè',
  },
  {
    slug: 'aventus-300-gr',
    fragranticaId: 9828,
    basis: 'inspired',
    note: 'inspired by Creed Aventus',
  },
  {
    slug: 'pink-molecule-090-300',
    fragranticaId: 25474,
    basis: 'inspired',
    note: 'inspired by ZARKOPERFUME Pink Molécule 090.09',
  },
  {
    slug: 'baccarat-300',
    fragranticaId: 33519,
    basis: 'inspired',
    note: 'inspired by Maison Francis Kurkdjian Baccarat Rouge 540',
  },
  {
    slug: 'black-afgano-300',
    fragranticaId: 6472,
    basis: 'inspired',
    note: 'inspired by Nasomatto Black Afgano',
  },
  {
    slug: '50-ganymede',
    fragranticaId: 54720,
    basis: 'inspired',
    note: 'inspired by Marc-Antoine Barrois Ganymede',
  },
  {
    slug: '50-baccarat',
    fragranticaId: 33519,
    basis: 'inspired',
    note: 'inspired by Maison Francis Kurkdjian Baccarat Rouge 540',
  },
  { slug: 'ciu-73448', fragranticaId: null, basis: 'house' },
  { slug: 'atelier-cologne', fragranticaId: null, basis: 'house' },
  { slug: 'tzd-44196', fragranticaId: null, basis: 'house' },
  { slug: 'prada-candy', fragranticaId: 12426, basis: 'inspired', note: 'inspired by Prada Candy' },
  {
    slug: 'elixir-des-merveilles',
    fragranticaId: 3168,
    basis: 'inspired',
    note: 'inspired by Hermès Elixir des Merveilles',
  },
  {
    slug: 'light-blue-2',
    fragranticaId: 485,
    basis: 'inspired',
    note: 'inspired by Dolce & Gabbana Light Blue',
  },
  { slug: 'cocaina', fragranticaId: null, basis: 'house' },
  { slug: 'le-blanc', fragranticaId: null, basis: 'house' },
  {
    slug: 'mango-skin-2',
    fragranticaId: 49305,
    basis: 'inspired',
    note: 'inspired by Vilhelm Parfumerie Mango Skin',
  },
  {
    slug: 'wood-sage-sea-salt-2',
    fragranticaId: 25529,
    basis: 'inspired',
    note: 'inspired by Jo Malone London Wood Sage & Sea Salt',
  },
  {
    slug: 'hayati-2',
    fragranticaId: null,
    basis: 'unresolved',
    note: "labor's own car perfume, not the Attar Collection bottle",
  },
  {
    slug: 'lost-cherry-2',
    fragranticaId: 51411,
    basis: 'inspired',
    note: 'inspired by Tom Ford Lost Cherry',
  },
  { slug: 'tygar-2', fragranticaId: 41222, basis: 'inspired', note: 'inspired by Bvlgari Tygar' },
  {
    slug: 'svecha-aroma',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Creation-brand candle; no Fragrantica page',
  },
  { slug: 'uew-77664', fragranticaId: null, basis: 'house' },
  { slug: '20', fragranticaId: null, basis: 'house' },
  { slug: '15', fragranticaId: null, basis: 'house' },
  { slug: 'savon-500', fragranticaId: null, basis: 'house' },
  {
    slug: 'chanel-tendre',
    fragranticaId: 8069,
    basis: 'inspired',
    note: 'inspired by Chanel Chance Eau Tendre — https://www.fragrantica.com/perfume/Chanel/Chance-Eau-Tendre-8069.html; 45092, first given here, is Lalique Tendre (the shop’s `tendre`)',
  },
  { slug: 'nature-function', fragranticaId: null, basis: 'house' },
  {
    slug: 'black-prince',
    fragranticaId: 51109,
    basis: 'inspired',
    note: 'inspired by Parfums Genty Black Prince',
  },
  {
    slug: 'baccarat',
    fragranticaId: 33519,
    basis: 'inspired',
    note: 'inspired by Maison Francis Kurkdjian Baccarat Rouge 540',
  },
  { slug: 'aventus-2', fragranticaId: 9828, basis: 'inspired', note: 'inspired by Creed Aventus' },
  { slug: 'ywu-88819', fragranticaId: null, basis: 'house' },
  {
    slug: '50',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'Creation-brand spray; wrong-product-images.ts already found no verified id',
  },
  { slug: '10', fragranticaId: null, basis: 'house' },
  { slug: 'black-earth', fragranticaId: null, basis: 'house' },
  { slug: 'green-scent', fragranticaId: null, basis: 'house' },
  { slug: 'thermal-spa-2', fragranticaId: null, basis: 'house' },
  { slug: 'ctu-18189', fragranticaId: null, basis: 'house' },
  { slug: 'zed-87190', fragranticaId: null, basis: 'house' },
  { slug: 'xrn-92860', fragranticaId: null, basis: 'house' },
  { slug: 'prs-28742', fragranticaId: null, basis: 'house' },
  { slug: 'lv', fragranticaId: null, basis: 'house' },
  {
    slug: 'creation',
    fragranticaId: null,
    basis: 'unresolved',
    note: 'MIX is not a Fragrantica-listed house',
  },
  {
    slug: '120',
    fragranticaId: null,
    basis: 'unresolved',
    note: "MIX-brand diffuser refill; wrong-product-images.ts already notes it isn't a perfume",
  },
  { slug: 'tendre', fragranticaId: 45092, basis: 'corrected' },
  {
    slug: 'devil-s-intrigue',
    fragranticaId: 52792,
    basis: 'search',
    note: "Haute Fragrance Company HFC Devil's Intrigue — https://www.fragrantica.com/perfume/Haute-Fragrance-Company-HFC/Devil-s-Intrigue-52792.html",
  },
  {
    slug: 'torino-22',
    fragranticaId: 77059,
    basis: 'search',
    note: 'Xerjoff Torino22 — https://www.fragrantica.com/perfume/Xerjoff/Torino22-77059.html',
  },
  { slug: 'bois-imperial', fragranticaId: 64338, basis: 'corrected' },
  { slug: 'elysium', fragranticaId: 96989, basis: 'spree' },
  { slug: 'silver-mountain', fragranticaId: 472, basis: 'corrected' },
  {
    slug: 'pink-molecule-090',
    fragranticaId: 25474,
    basis: 'search',
    note: 'ZARKOPERFUME PINK MOLéCULE 090.09 — https://www.fragrantica.com/perfume/ZARKOPERFUME/PINK-MOLeCULE-090-09-25474.html',
  },
  { slug: 'molecule-02-2', fragranticaId: 3606, basis: 'spree' },
  { slug: 'fabulous', fragranticaId: 46513, basis: 'spree' },
  { slug: 'black-phantom', fragranticaId: 43632, basis: 'spree' },
  {
    slug: 'apple-brandy',
    fragranticaId: 22614,
    basis: 'search',
    note: 'By Kilian Apple Brandy (base) — https://www.fragrantica.com/perfume/By-Kilian/Apple-Brandy-22614.html',
  },
  {
    slug: 'kissing-burns-6-4',
    fragranticaId: 50496,
    basis: 'search',
    note: 'By Kilian Kissing Burns 6.4 Calories A Minute. Wanna Workout? — https://www.fragrantica.com/perfume/By-Kilian/Kissing-Burns-6-4-Calories-A-Minute-Wanna-Workout-50496.html',
  },
  { slug: 'love-don-t-by-shy', fragranticaId: 4322, basis: 'corrected' },
  { slug: 'angel-s-share', fragranticaId: 62615, basis: 'corrected' },
  { slug: 'roses-on-ice', fragranticaId: 62616, basis: 'spree' },
  { slug: 'l-heure-verte', fragranticaId: 68324, basis: 'spree' },
  { slug: 'rolling-in-love', fragranticaId: 56402, basis: 'spree' },
  {
    slug: 'divine-blossom',
    fragranticaId: 70785,
    basis: 'search',
    note: 'Haute Fragrance Company HFC Divine Blossom — https://www.fragrantica.com/perfume/Haute-Fragrance-Company-HFC/Divine-Blossom-70785.html',
  },
  { slug: 'montabaco-2', fragranticaId: 16896, basis: 'corrected' },
  { slug: 'ombre-leather', fragranticaId: 50239, basis: 'corrected' },
  { slug: 'smoke-cherry', fragranticaId: 78578, basis: 'corrected' },
  {
    slug: 'good-girl-gone-bad',
    fragranticaId: 15924,
    basis: 'search',
    note: 'By Kilian Good Girl Gone Bad (base) — https://www.fragrantica.com/perfume/By-Kilian/Good-Girl-Gone-Bad-15924.html',
  },
  {
    slug: 'baccarat-rouge-540',
    fragranticaId: 33519,
    basis: 'search',
    note: "Maison Francis Kurkdjian Baccarat Rouge 540 (base eau de parfum, 2015) — https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html; spree gave 46066, the Extrait de Parfum, but the name has no 'Extrait'",
  },
  {
    slug: 'n4-apres-l-amour',
    fragranticaId: 53742,
    basis: 'search',
    note: "Thomas Kosmala No.4 Après l'Amour EDP — https://www.fragrantica.com/perfume/Thomas-Kosmala/No-4-Apres-l-Amour-Eau-de-Parfum-53742.html; our row's brand field says 'Histoires de Parfums' but that's a mismatch — the sibling SKU 'n4-apr-s-l-amour' is correctly attributed to Thomas Kosmala and already carries this id",
  },
  { slug: 'indian-venus', fragranticaId: 52793, basis: 'spree' },
  { slug: 'musk-therapy', fragranticaId: 96606, basis: 'spree' },
  { slug: 'rehab', fragranticaId: 50351, basis: 'spree' },
  { slug: 'imagination-2', fragranticaId: 67370, basis: 'spree' },
  { slug: 'aventus-man', fragranticaId: 9828, basis: 'corrected' },
  {
    slug: 'limmensite',
    fragranticaId: 49751,
    basis: 'search',
    note: "Louis Vuitton L'Immensité — https://www.fragrantica.com/perfume/Louis-Vuitton/L-Immensite-49751.html",
  },
  { slug: 'attar-musc-kashmir', fragranticaId: 102064, basis: 'spree' },
  { slug: 'blue', fragranticaId: 107353, basis: 'spree' },
  { slug: 'lost-cherry-5', fragranticaId: 51411, basis: 'spree' },
];
