// The olfactive families, and which note belongs to which.
//
// The imported classification was a guess made by whatever scraped it, and it
// showed on the page: peach, mango, pineapple, plum and raspberry were filed
// under GREEN; cinnamon, clove, ginger and saffron under AROMATIC; and ORIENTAL
// was a bin holding musks, resins, ambers and every spice at once — a heading
// that told a customer nothing, because nothing was excluded from it. 127 notes
// carried no family at all.
//
// So the families here are the ones a nose actually uses, and the assignment is
// written out rather than derived. A note belongs to the family its material
// belongs to: neroli and petitgrain are citrus because they come off the bitter
// orange tree, cassis is fruity however green it smells, and frankincense sits
// with the other resins rather than with smoke.
//
// `scripts/reclassify-note-families.ts` writes this into the database and
// reports any slug that appears in one and not the other, so an import that
// adds notes cannot silently leave them unfiled.

export const NOTE_FAMILIES = [
  'floral',
  'woody',
  'gourmand',
  'fruity',
  'citrus',
  'spicy',
  'aromatic',
  'balsamic',
  'green',
  'musky',
  'aquatic',
  'smoky',
  'mineral',
  'mossy',
  'leather',
] as const;

export type NoteFamily = (typeof NOTE_FAMILIES)[number];

/** The families offered as one-tap filters. Ordered by how much of the shop each covers. */
export const FAMILY_FILTERS: readonly NoteFamily[] = [
  'floral',
  'woody',
  'gourmand',
  'fruity',
  'citrus',
  'spicy',
  'aquatic',
  'smoky',
  'leather',
];

const FAMILY_MEMBERS: Record<NoteFamily, readonly string[]> = {
  citrus: [
    'amalfi-lemon',
    'bergamot',
    'bitter-orange',
    'blood-mandarin',
    'blood-orange',
    'calabrian-bergamot',
    'california-orange',
    'citron',
    'citrus',
    'citruses',
    'clementine',
    'grapefruit',
    'kumquat',
    'lemon',
    'lemon-zest',
    'lime',
    'litsea-cubeba',
    'mandarin',
    'mandarin-orange',
    'neroli',
    'orange',
    'petitgrain',
    'pomelo',
    'sicilian-bergamot',
    'sicilian-lemon',
    'sicilian-orange',
    'tangerine',
    'tunisian-neroli',
    'verbena',
    'vervain',
    'yuzu',
  ],

  floral: [
    'african-orange-flower',
    'bellflower',
    'bitter-orange-blossom',
    'black-elder',
    'black-orchid',
    'blue-lotus',
    'broom',
    'bulgarian-rose',
    'cactus-flower',
    'carnation',
    'champaca',
    'chinese-jasmine',
    'chinese-osmanthus',
    'cyclamen',
    'damask-rose',
    'egyptian-jasmine',
    'floral-bouquet',
    'floral-notes',
    'freesia',
    'gardenia',
    'geranium',
    'grasse-rose',
    'hawthorn',
    'hedione',
    'heliotrope',
    'honeysuckle',
    'hyacinth',
    'immortelle',
    'indian-jasmine',
    'indian-tuberose',
    'iris',
    'jasmine',
    'jasmine-sambac',
    'lemon-blossom',
    'lilac',
    'lily',
    'lily-of-the-valley',
    'lime-linden-blossom',
    'lotus',
    'magnolia',
    'mahonial',
    'marigold',
    'may-rose',
    'mignonette',
    'mimosa',
    'mock-orange',
    'mystikal',
    'narcissus',
    'orange-blossom',
    'orchid',
    'orris',
    'orris-root',
    'osmanthus',
    'peony',
    'petalia',
    'pink-lotus',
    'pink-peony',
    'pink-rose',
    'pomarose',
    'rose',
    'rose-de-mai',
    'rose-geranium',
    'rose-oxide',
    'rose-petals',
    'rose-water',
    'sweet-pea',
    'taif-rose',
    'tiare-flower',
    'tuberose',
    'tunisian-orange-blossom',
    'turkish-rose',
    'violet',
    'violet-root',
    'water-hyacinth',
    'water-jasmine',
    'water-lily',
    'white-flowers',
    'white-rose',
    'ylang-ylang',
  ],

  fruity: [
    'apple',
    'apricot',
    'black-cherry',
    'black-currant',
    'blackberry',
    'blackcurrant',
    'cassis',
    'cherry',
    'cherry-liqueur',
    'dates',
    'dried-fruits',
    'exotic-fruits',
    'fig',
    'fruits',
    'fruity-notes',
    'granny-smith-apple',
    'grapes',
    'green-apple',
    'litchi',
    'lychee',
    'mango',
    'melon',
    'passionfruit',
    'peach',
    'pear',
    'pineapple',
    'plum',
    'quince',
    'raspberry',
    'red-berries',
    'red-currant',
    'red-fruits',
    'rhubarb',
    'rhuburb',
    'sapodilla',
    'sour-cherry',
    'strawberry',
    'white-peach',
  ],

  green: [
    'bamboo',
    'black-tea',
    'carrot',
    'carrot-seeds',
    'chinese-black-tea',
    'chlorophyll',
    'cucumber',
    'fig-leaf',
    'galbanum',
    'grass',
    'green-notes',
    'green-tea',
    'hay',
    'ivy',
    'mate',
    'matcha-tea',
    'olive',
    'oolong-tea',
    'rooibos-tea',
    'tea',
    'violet-leaf',
    'violet-leaves',
    'white-tea',
  ],

  aromatic: [
    'absinthe',
    'almdudler',
    'angelica',
    'anise',
    'artemisia',
    'basil',
    'bay-leaf',
    'cannabis',
    'chamomile',
    'clary-sage',
    'coumarin',
    'davana',
    'eucalyptus',
    'fennel',
    'herbal-notes',
    'juniper',
    'juniper-berries',
    'juniper-berry',
    'lavender',
    'licorice',
    'mastic-or-lentisque',
    'mint',
    'oregano',
    'peppermint',
    'rosemary',
    'sage',
    'star-anise',
    'thyme',
  ],

  spicy: [
    'aromatic-spices',
    'black-pepper',
    'cardamom',
    'cardamon',
    'ceylon-cinnamon',
    'chili-pepper',
    'cinnamon',
    'clove',
    'cloves',
    'coriander',
    'cumin',
    'ginger',
    'guatemalan-cardamom',
    'indonesian-nutmeg',
    'nigerian-ginger',
    'nutmeg',
    'paprika',
    'pepper',
    'pimento',
    'pink-pepper',
    'safraleine',
    'saffron',
    'sichuan-pepper',
    'spices',
    'spicy-notes',
    'timur',
    'white-pepper',
  ],

  woody: [
    'agarwood',
    'agarwood-oud',
    'akigalawood',
    'amyris',
    'assam-oud',
    'atlas-cedar',
    'australian-sandalwood',
    'balsam-fir',
    'birch',
    'blackwood',
    'blonde-woods',
    'brazilian-rosewood',
    'cambodian-oud',
    'cashmeran',
    'cashmere-wood',
    'cedar',
    'cedar-needles',
    'cedarwood',
    'cypress',
    'cypriol',
    'cypriol-oil-or-nagarmotha',
    'driftwood',
    'dry-wood',
    'ebony',
    'ebony-tree',
    'fir',
    'gaiac',
    'georgywood',
    'guaiac-wood',
    'haitian-vetiver',
    'indonesian-patchouli-leaf',
    'iso-e-super',
    'java-vetiver-oil',
    'mahogany',
    'mysore-sandalwood',
    'oak',
    'oud',
    'palisander-rosewood',
    'papyrus',
    'patchouli',
    'patchouli-leaf',
    'pepperwood',
    'pine',
    'pine-needles',
    'pine-tree',
    'sandal',
    'sandal-mysore',
    'sandalwood',
    'sequoia',
    'tahitian-vetiver',
    'teak-wood',
    'vetiver',
    'virginia-cedar',
    'virginian-cedar',
    'white-cedar-extract',
    'white-sandalwood',
    'white-wood',
    'white-woods',
    'woodsy-notes',
    'woody-notes',
  ],

  balsamic: [
    'amber',
    'ambergris',
    'ambermax',
    'amberwood',
    'ambrofix',
    'ambroxan',
    'benzoin',
    'black-amber',
    'cetalox',
    'copal',
    'elemi',
    'frankincense',
    'french-labdanum',
    'gurjan-balsam',
    'incense',
    'labdanum',
    'myrrh',
    'olibanum',
    'opoponax',
    'peru-balsam',
    'resins',
    'styrax',
    'tolu-balsam',
  ],

  gourmand: [
    'almond',
    'almond-milk',
    'almond-tree',
    'bitter-almond',
    'brandy',
    'brown-sugar',
    'butter',
    'cacao',
    'cacao-butter',
    'cacao-pod',
    'candied-almond',
    'caramel',
    'champagne',
    'chestnut',
    'chocolate',
    'cocoa',
    'coconut',
    'coconut-milk',
    'coffee',
    'cognac',
    'cream',
    'dark-chocolate',
    'gummy-candies',
    'hazelnut',
    'honey',
    'icing-pink',
    'kulfi',
    'lactones',
    'liquor',
    'bourbon-vanilla',
    'madagascar-vanilla',
    'maple-syrup',
    'marshmallow',
    'milk',
    'popcorn',
    'praline',
    'rice',
    'rum',
    'sesame',
    'soybean',
    'sugar',
    'sugar-cane',
    'tonka',
    'tonka-bean',
    'vanila',
    'vanilla',
    'vanilla-bean',
    'vanilla-pod',
    'vanilla-sugar',
    'vanille',
    'vodka',
    'whipped-cream',
    'whiskey',
    'white-rum',
  ],

  musky: [
    'aldehydes',
    'ambrette',
    'ambrette-musk-mallow',
    'ambrettolide',
    'animal-notes',
    'black-musk',
    'cashmere-musk',
    'castoreum',
    'civet',
    'helvetolide',
    'muscone',
    'musk',
    'musk-mallow',
    'powdery-notes',
    'velvione',
    'white-musk',
  ],

  aquatic: [
    'aquatic-notes',
    'calone',
    'marine-notes',
    'ozone',
    'ozonic-notes',
    'rain',
    'salt',
    'sea-notes',
    'sea-water',
    'seaweed',
    'water-notes',
    'watery-notes',
  ],

  smoky: [
    'birch-tar',
    'cade-oil',
    'coal',
    'palo-santo',
    'smoke',
    'tobacco',
    'tobacco-blossom',
    'tobacco-leaf',
    'white-tobacco',
  ],

  mineral: [
    'concrete',
    'ink',
    'lava',
    'metallic-notes',
    'mineral-notes',
    'paper',
    'spray-paint',
    'stone',
  ],

  mossy: ['earthy-notes', 'evernyl', 'moss', 'oak-moss', 'oakmoss', 'soil-tincture'],

  leather: ['black-leather', 'leather', 'suede', 'white-suede'],
};

/** slug → family, inverted from the lists above so the source of truth stays readable. */
export const NOTE_FAMILY_BY_SLUG: ReadonlyMap<string, NoteFamily> = new Map(
  (Object.entries(FAMILY_MEMBERS) as [NoteFamily, readonly string[]][]).flatMap(([family, slugs]) =>
    slugs.map((slug): [string, NoteFamily] => [slug, family]),
  ),
);
